# Shell variables
# Generated by 'wal'
wallpaper="/home/brent/Pictures/Wallpapers/Wallpaper.jpg"

# Special
background='#000D1B'
foreground='#bfc2c6'
cursor='#bfc2c6'

# Colors
color0='#000D1B'
color1='#875742'
color2='#9f6c50'
color3='#013b6f'
color4='#004575'
color5='#0178a3'
color6='#0d9ab7'
color7='#8c9297'
color8='#57606b'
color9='#B47458'
color10='#D4916B'
color11='#024F94'
color12='#015D9D'
color13='#02A1DA'
color14='#12CEF5'
color15='#bfc2c6'

# FZF colors
export FZF_DEFAULT_OPTS="
    $FZF_DEFAULT_OPTS
    --color fg:7,bg:0,hl:1,fg+:232,bg+:1,hl+:255
    --color info:7,prompt:2,spinner:1,pointer:232,marker:1
"

# Fix LS_COLORS being unreadable.
export LS_COLORS="${LS_COLORS}:su=30;41:ow=30;42:st=30;44:"
