--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/brent/Pictures/Wallpapers/wallhaven-5gylo8.jpg"

-- Special
background="#000D1B"
foreground="#a1d9e5"
cursor="#a1d9e5"

-- Colors
color0="#000D1B"
color1="#B47458"
color2="#D4916B"
color3="#024F94"
color4="#015D9D"
color5="#02A1DA"
color6="#12CEF5"
color7="#a1d9e5"
color8="#7097a0"
color9="#B47458"
color10="#D4916B"
color11="#024F94"
color12="#015D9D"
color13="#02A1DA"
color14="#12CEF5"
color15="#a1d9e5"
