--Place this file in your .xmonad/lib directory and import module Colors into .xmonad/xmonad.hs config
--The easy way is to create a soft link from this file to the file in .xmonad/lib using ln -s
--Then recompile and restart xmonad.

module Colors
    ( wallpaper
    , background, foreground, cursor
    , color0, color1, color2, color3, color4, color5, color6, color7
    , color8, color9, color10, color11, color12, color13, color14, color15
    ) where

-- Shell variables
-- Generated by 'wal'
wallpaper="/home/brent/Pictures/Wallpapers/Wallpaper.jpg"

-- Special
background="#000D1B"
foreground="#bfc2c6"
cursor="#bfc2c6"

-- Colors
color0="#000D1B"
color1="#875742"
color2="#9f6c50"
color3="#013b6f"
color4="#004575"
color5="#0178a3"
color6="#0d9ab7"
color7="#8c9297"
color8="#57606b"
color9="#B47458"
color10="#D4916B"
color11="#024F94"
color12="#015D9D"
color13="#02A1DA"
color14="#12CEF5"
color15="#bfc2c6"
